version: '3.9'
services:
  backend:
    build: ../backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ../backend/src:/app/src
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
